apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: placeholder-scaledobject
spec:
  scaleTargetRef:
    name: placeholder
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: placeholder
      metadata:
        key: value
